"""The Fmod constant, e. g. the defines which have only one value."""
CODEC_WAVEFORMAT_VERSION = 3
DSP_GETPARAM_VALUESTR_LENGTH = 32
MAX_CHANNEL_WIDTH = 32
MAX_LISTENERS = 8
PORT_INDEX_NONE = -1
REVERB_MAXINSTANCES = 4